### ISSUE TITLE
About CloudSamplingTools::resampleCloudSpatially

### ISSUE THREAD

**Issue by ChoEunHyeon** [CloudCompare/CCCoreLib#98]
hello. 
I am a student who is studying subsampling by looking at the code.
Could I get a paper related to code logic or an explanation of how the logic works?
I would like to understand CloudSamplingTools::resampleCloudSpatially.

**Comment by dgirardeau** [comment]
So this method should be called subsampleCloudSpatially actually.

We first mark all the points as 'to be kept'. Then we pick a first point, and flag all its neighbors within a sphere of a given radius as 'to be discarded'. Then we look for the next point in the cloud still flagged as 'to be kept', and we flag all its neighbors as 'to be discarded'. And we repeat the process until all points are processed.

There's also a variation of the algorithm where we change the radius based on an associated scalar field (so that it's possible to keep more points - i.e. reduce the radius - in areas with a high curvature for instance).
